name: Bug report
description: Report a defect or regression.
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is the bug?
      placeholder: Describe the issue concisely.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: Provide step-by-step instructions.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Include OS, browser (if relevant), branch, commit hash.
      placeholder: OS: 
        Browser: 
        Branch: 
        Commit:
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs/screenshots
      description: Add any relevant logs or screenshots.
    validations:
      required: false
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - S1
        - S2
        - S3
        - S4
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Affected area
      options:
        - backend
        - frontend
        - infra
        - docs
    validations:
      required: true
